language: python
python:
    - "3.5"
install:
    - sudo apt-get install -qq redis-server && redis-server &
    - pip install -r deploy/requirements.txt
    - mkdir log test_case upload
    - cp oj/custom_settings.example.py oj/custom_settings.py
    - echo "SECRET_KEY=\"`cat /dev/urandom | head -1 | md5sum | head -c 32`\"" >> oj/custom_settings.py
    - python manage.py migrate
    - python manage.py initadmin
script:
    - flake8 .
    - coverage run --include="$PWD/*" manage.py test
    - coverage report
notifications:
    slack: onlinejudgeteam:BzBz8UFgmS5crpiblof17K2W
